# Generated by Django 4.2.3 on 2023-07-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_title', models.CharField(max_length=300, verbose_name='Solution Title')),
                ('sol_description', models.TextField(verbose_name='Solution Description')),
            ],
        ),
        migrations.CreateModel(
            name='Bug_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=300, verbose_name='Bug Title')),
                ('project_name', models.CharField(max_length=300, verbose_name='Bug Title')),
                ('tester_code', models.TextField(blank=True, verbose_name='Tester code')),
                ('contact', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('bug_priority', models.CharField(max_length=20, verbose_name='Bug Priority')),
                ('bug_status', models.CharField(max_length=20, verbose_name='Bug Department')),
                ('bug_date', models.DateTimeField(verbose_name='Bug Date')),
                ('query_department', models.CharField(max_length=50, verbose_name='Bug Department')),
                ('bug_description', models.TextField(verbose_name='Bug Description')),
                ('bug_solutions', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.bug_solution')),
            ],
        ),
    ]
