# Generated by Django 4.2.3 on 2023-07-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bug_query_bug_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_priority', models.CharField(max_length=20, verbose_name='Bug Priority')),
            ],
        ),
        migrations.CreateModel(
            name='Bug_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_status', models.CharField(max_length=20, verbose_name='Bug Department')),
            ],
        ),
        migrations.AlterField(
            model_name='bug_query',
            name='bug_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.bug_priority'),
        ),
        migrations.AlterField(
            model_name='bug_query',
            name='bug_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.bug_status'),
        ),
    ]
