# Generated by Django 4.2.3 on 2023-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bug_priority_bug_status_alter_bug_query_bug_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_status',
            name='bug_status',
            field=models.CharField(max_length=20, verbose_name='Bug Status'),
        ),
    ]
