# Generated by Django 4.2.3 on 2023-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_bug_status_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_query',
            name='project_name',
            field=models.CharField(max_length=300, verbose_name='Project Name'),
        ),
    ]
