# Generated by Django 4.2.3 on 2023-07-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_bug_query_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_query',
            name='bug_solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.bug_solution'),
        ),
        migrations.AlterField(
            model_name='bug_query',
            name='tester_code',
            field=models.TextField(blank=True, null=True, verbose_name='Tester code'),
        ),
    ]
