# Generated by Django 4.2.3 on 2023-07-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bug_query_bug_solutions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_search', models.CharField(blank=True, max_length=300, verbose_name='Search the Bug')),
            ],
        ),
    ]
