# Generated by Django 4.2.3 on 2023-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_bug_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_solution',
            name='sol_description',
            field=models.TextField(max_length=500, verbose_name='Solution Description'),
        ),
        migrations.AlterField(
            model_name='bug_solution',
            name='sol_title',
            field=models.CharField(max_length=500, verbose_name='Solution Title'),
        ),
    ]
