# Generated by Django 4.2.3 on 2023-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_bug_solution_sol_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug_query',
            name='bug_solutions',
        ),
        migrations.AlterField(
            model_name='bug_solution',
            name='sol_description',
            field=models.TextField(verbose_name='Solution Description'),
        ),
    ]
