# Generated by Django 4.1.3 on 2023-07-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_bug_query_bug_solutions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug_query',
            name='bug_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.bug_solution'),
        ),
    ]
